/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.panel_views;

/**
 *
 * @author alexo
 */
public class DepartmentView extends javax.swing.JPanel {

    /**
     * Creates new form DepartmentView
     */
    public DepartmentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empListLabel = new javax.swing.JLabel();
        empScrollPane = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        deptsComboBox = new javax.swing.JComboBox<>();
        refreshButton = new javax.swing.JButton();
        separator1 = new javax.swing.JSeparator();
        newDeptLabel = new javax.swing.JLabel();
        newDeptTextField = new javax.swing.JTextField();
        rightsComboBox = new javax.swing.JComboBox<>();
        addDeptButton = new javax.swing.JButton();
        separator2 = new javax.swing.JSeparator();
        updateDeptLabel = new javax.swing.JLabel();
        selectDeptComboBox = new javax.swing.JComboBox<>();
        newNameTextField = new javax.swing.JTextField();
        newRightComboBox = new javax.swing.JComboBox<>();
        updateDeptButton = new javax.swing.JButton();
        separator3 = new javax.swing.JSeparator();
        deleteDeptLabel = new javax.swing.JLabel();
        selectDeptDelComboBox = new javax.swing.JComboBox<>();
        deleteDeptButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empListLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        empListLabel.setText("Listado empleados");
        add(empListLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 17, -1, -1));

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Fecha contrato", "Dirección", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        empScrollPane.setViewportView(empTable);

        add(empScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 80, 777, 229));

        add(deptsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 46, 214, 28));

        refreshButton.setBackground(new java.awt.Color(0, 134, 190));
        refreshButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh_icon.png"))); // NOI18N
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 46, 50, 28));
        add(separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 324, 777, 10));

        newDeptLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        newDeptLabel.setText("Nuevo departamento");
        add(newDeptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 340, -1, -1));

        newDeptTextField.setText("Nombre");
        add(newDeptTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 369, 175, 30));

        add(rightsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 405, 175, 30));

        addDeptButton.setBackground(new java.awt.Color(0, 134, 190));
        addDeptButton.setForeground(new java.awt.Color(255, 255, 255));
        addDeptButton.setText("Añadir departamento");
        add(addDeptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 441, 175, 31));

        separator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 349, -1, 145));

        updateDeptLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        updateDeptLabel.setText("Modificar departamento");
        add(updateDeptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 340, 159, -1));

        add(selectDeptComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 369, 175, 30));

        newNameTextField.setText("Nuevo nombre");
        add(newNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 405, 150, 30));

        add(newRightComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 405, 175, 30));

        updateDeptButton.setBackground(new java.awt.Color(0, 134, 190));
        updateDeptButton.setForeground(new java.awt.Color(255, 255, 255));
        updateDeptButton.setText("Modificar departamento");
        add(updateDeptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 441, 175, 31));

        separator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(separator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 340, -1, 145));

        deleteDeptLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        deleteDeptLabel.setText("Eliminar departamento");
        add(deleteDeptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 340, -1, -1));

        add(selectDeptDelComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 369, 175, 30));

        deleteDeptButton.setBackground(new java.awt.Color(255, 0, 0));
        deleteDeptButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteDeptButton.setText("Eliminar departamento");
        add(deleteDeptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 405, 175, 31));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDeptButton;
    private javax.swing.JButton deleteDeptButton;
    private javax.swing.JLabel deleteDeptLabel;
    private javax.swing.JComboBox<String> deptsComboBox;
    private javax.swing.JLabel empListLabel;
    private javax.swing.JScrollPane empScrollPane;
    private javax.swing.JTable empTable;
    private javax.swing.JLabel newDeptLabel;
    private javax.swing.JTextField newDeptTextField;
    private javax.swing.JTextField newNameTextField;
    private javax.swing.JComboBox<String> newRightComboBox;
    private javax.swing.JButton refreshButton;
    private javax.swing.JComboBox<String> rightsComboBox;
    private javax.swing.JComboBox<String> selectDeptComboBox;
    private javax.swing.JComboBox<String> selectDeptDelComboBox;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JSeparator separator3;
    private javax.swing.JButton updateDeptButton;
    private javax.swing.JLabel updateDeptLabel;
    // End of variables declaration//GEN-END:variables
}
