/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.panel_views;

/**
 *
 * @author alexo
 */
public class RRHHView extends javax.swing.JPanel {

    /**
     * Creates new form RRHHView
     */
    public RRHHView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        titleLabel = new javax.swing.JLabel();
        fromDateChooser = new com.toedter.calendar.JDateChooser();
        untilDateChooser = new com.toedter.calendar.JDateChooser();
        deptComboBox = new javax.swing.JComboBox<>();
        empComboBox = new javax.swing.JComboBox<>();
        fromLabel = new javax.swing.JLabel();
        untilLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        empLabel = new javax.swing.JLabel();
        empScrollPane = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        Separator1 = new javax.swing.JSeparator();
        updateLabel = new javax.swing.JLabel();
        deptUpdateComboBox = new javax.swing.JComboBox<>();
        empUpdateComboBox = new javax.swing.JComboBox<>();
        newDeptLabel = new javax.swing.JLabel();
        newDeptComboBox = new javax.swing.JComboBox<>();
        newRolLabel = new javax.swing.JLabel();
        newRolComboBox = new javax.swing.JComboBox<>();
        newMailTextField = new javax.swing.JTextField();
        deleteEmpButton = new javax.swing.JButton();
        Separator2 = new javax.swing.JSeparator();
        addEmpLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        lastnameTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        deleteEmpButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        titleLabel.setText("Listado entradas/salidas");
        add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        add(fromDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 30));
        add(untilDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 30));

        add(deptComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 130, 30));

        add(empComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 160, 30));

        fromLabel.setText("Desde:");
        add(fromLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        untilLabel.setText("Hasta:");
        add(untilLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        deptLabel.setText("Departamento:");
        add(deptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        empLabel.setText("Empleado:");
        add(empLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Fecha", "Hora entrada", "Hora salida", "Horas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empScrollPane.setViewportView(empTable);

        add(empScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 630, 170));
        add(Separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 780, 10));

        updateLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        updateLabel.setText("Modificar empleado:");
        add(updateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 30));

        add(deptUpdateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 140, 30));

        add(empUpdateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 140, 30));

        newDeptLabel.setText("Nuevo departamento");
        add(newDeptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        add(newDeptComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 140, 30));

        newRolLabel.setText("Nuevo rol");
        add(newRolLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        add(newRolComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 140, 30));

        newMailTextField.setText("Nuevo email");
        add(newMailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 140, 30));

        deleteEmpButton.setBackground(new java.awt.Color(0, 134, 190));
        deleteEmpButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteEmpButton.setText("Añadir empleado");
        add(deleteEmpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 140, 30));
        add(Separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 780, 10));

        addEmpLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        addEmpLabel.setText("Añadir empleado");
        add(addEmpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 30));

        nameTextField.setText("Nombre");
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 100, 30));

        lastnameTextField.setText("Apellidos");
        add(lastnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 100, 30));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 140, 30));

        jTextField1.setText("email");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 320, 30));

        deleteEmpButton1.setBackground(new java.awt.Color(255, 0, 0));
        deleteEmpButton1.setForeground(new java.awt.Color(255, 255, 255));
        deleteEmpButton1.setText("Eliminar empleado");
        add(deleteEmpButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 130, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 10, 110));

        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 150, 30));

        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 270, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Eliminar empleado");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, 30));

        jButton1.setBackground(new java.awt.Color(0, 134, 190));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh_icon.png"))); // NOI18N
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 80, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JLabel addEmpLabel;
    private javax.swing.JButton deleteEmpButton;
    private javax.swing.JButton deleteEmpButton1;
    private javax.swing.JComboBox<String> deptComboBox;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JComboBox<String> deptUpdateComboBox;
    private javax.swing.JComboBox<String> empComboBox;
    private javax.swing.JLabel empLabel;
    private javax.swing.JScrollPane empScrollPane;
    private javax.swing.JTable empTable;
    private javax.swing.JComboBox<String> empUpdateComboBox;
    private com.toedter.calendar.JDateChooser fromDateChooser;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox<String> newDeptComboBox;
    private javax.swing.JLabel newDeptLabel;
    private javax.swing.JTextField newMailTextField;
    private javax.swing.JComboBox<String> newRolComboBox;
    private javax.swing.JLabel newRolLabel;
    private javax.swing.JLabel titleLabel;
    private com.toedter.calendar.JDateChooser untilDateChooser;
    private javax.swing.JLabel untilLabel;
    private javax.swing.JLabel updateLabel;
    // End of variables declaration//GEN-END:variables
}
