/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panelViews;

/**
 *
 * @author alexo
 */
public class RRHHView extends javax.swing.JPanel {

    /**
     * Creates new form RRHHView
     */
    public RRHHView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addEmployeeLabel = new javax.swing.JLabel();
        addEmployeeSeparator = new javax.swing.JSeparator();
        surname2TextField = new javax.swing.JTextField();
        mailTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        surnameTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addEmployeeLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        addEmployeeLabel.setText("Añadir empleado");
        add(addEmployeeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 30));

        addEmployeeSeparator.setBackground(new java.awt.Color(0, 134, 190));
        addEmployeeSeparator.setForeground(new java.awt.Color(0, 134, 190));
        add(addEmployeeSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 410, 10));

        surname2TextField.setForeground(new java.awt.Color(204, 204, 204));
        surname2TextField.setText("Apellido2");
        add(surname2TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 110, 30));

        mailTextField.setForeground(new java.awt.Color(204, 204, 204));
        mailTextField.setText("email");
        add(mailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 370, 30));

        nameTextField.setForeground(new java.awt.Color(204, 204, 204));
        nameTextField.setText("nombre");
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 30));

        surnameTextField.setForeground(new java.awt.Color(204, 204, 204));
        surnameTextField.setText("Apellido1");
        add(surnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 110, 30));

        phoneTextField.setForeground(new java.awt.Color(204, 204, 204));
        phoneTextField.setText("Tlf.");
        add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 110, 30));

        AddButton.setBackground(new java.awt.Color(0, 134, 190));
        AddButton.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Añadir");
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 110, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel addEmployeeLabel;
    private javax.swing.JSeparator addEmployeeSeparator;
    private javax.swing.JTextField mailTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField surname2TextField;
    private javax.swing.JTextField surnameTextField;
    // End of variables declaration//GEN-END:variables
}
